name: Professions
version: ${project.version}
main: moldas.professions.Professions
api-version: 1.16
authors: [ Moldas, AT13, Ximure ]
description: Professions for minecraft
commands:
  getprof:
    description: Your description
    usage: /<command>
  setplayerprof:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  helpprof:
    description: Your description
    usage: /<command>
  leaveprof:
    description: Your description
    usage: /<command>
  deleteplayerprof:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  myprof:
    description: Your description
    usage: /<command>
  changestat:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  mystats:
    description: Your description
    usage: /<command>
